version: "3.1"
services:
  qianniu-nginx:
    container_name: qianniu-nginx
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - qianniu_network
    volumes:
      - ./html/qianniu/dist:/home/qianniu/projects/homepage
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/ssl:/etc/ssl

networks:
  qianniu_network:
    driver: bridge
